feuerwehr/urls.py
"""feuerwehr URL Configuration
"""
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
from . import views
from .signals import on_alarm_create_cb, on_location_create_cb

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.HomepageView.as_view(), name="home"),
    path('alarm/', views.AlarmListView.as_view(), name="alarm-list"),
    path('alarm/create', views.AlarmCreateView.as_view(), name="alarm-create"),
    path('alarm/<int:year>/<int:no>/', views.AlarmDetailView.as_view(), name="alarm-detail"),
    path('alarm/<int:no>/', views.AlarmDetailView.as_view(), name="alarm-detail"),
    path('alarm/<int:year>/<int:no>/edit', views.AlarmUpdateView.as_view(), name="alarm-edit"),
    path('u/', views.UserListView.as_view(), name="user-list"),
    path('u/<str:username>/', views.UserDetailView.as_view(), name="user-detail"),
    path('map/', include('maps.urls')),
    path('accounts/login/', auth_views.LoginView.as_view(), name="login"),
    path('accounts/password_reset/', auth_views.PasswordResetView.as_view(), name="password_reset"),
    path('accounts/password_reset_done/', auth_views.PasswordResetConfirmView.as_view(),
         name="password_reset_confirm"),
    #path('o/', include('oauth2_provider.urls', namespace='oauth2_provider')),
]
# only in debug mode provide static files: + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

from django.db.models import signals
from .models import Alarm, Location
# registering signals with the model's string label
signals.pre_save.connect(on_alarm_create_cb, sender=Alarm)
signals.pre_save.connect(on_location_create_cb, sender=Location)

maps/urls.py
""" (comments)
"""
from django.urls import path
from . import views

urlpatterns = [
    path(r'', views.MarkersMapView.as_view(), name="default-map"),
]

feuerwehr/models.py
from django.conf import settings
from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse
from django.utils.translation import gettext_lazy as _


from datetime import datetime, timedelta
import logging
from pytz import timezone

# The timezone as configured in the django settings
cur_tz = timezone(settings.TIME_ZONE)

def user_get_absolute_url(self):
    return reverse('user-detail', kwargs={"username": self.username})
User.get_absolute_url = user_get_absolute_url

def user_get_name(self):
    same_f_name = User.objects.filter(first_name=self.first_name)
    if len(same_f_name) == 1 and self.first_name > "":
        return self.first_name
    if self.last_name > "":
        return f"{self.first_name} {self.last_name[0]}."
    return self.username
User.__str__ = user_get_name


DEPT = [
    (0, ""),
    (1, "Einsatzabteilung"),
    (2, "Ehrenabteilung"),
    (3, "Reserveabteilung"),
    (4, "JF"),
]


class Person(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    dep  = models.SmallIntegerField(default=0)
    roles = models.ManyToManyField('Role', blank=True)

    def __str__(self):
        return str(self.user)

class Attendance(models.IntegerChoices):
    BESTÄTIGT = 1, _("Bestätigt")
    YES = 2, _("Zugesagt")
    NO = 3, _("Abgesagt")
    __empty__ = _("Unbekannt")


class Location(models.Model):
    lat = models.FloatField()
    lon = models.FloatField()
    # sanitized: all lowercase and str.->straße
    address = models.CharField(max_length=255, blank=True)
    # lat/lon get filled in in signals.py
    def __str__(self):
        return self.address

    class Meta:
        constraints = [
            models.UniqueConstraint(fields=['lat', 'lon'],
                                    name='unique_location')
            ]


class Alarm(models.Model):
    def autoinc_num(*args,**kwargs):
        """Provide the next free alarm number"""
        maxalarm = Alarm.objects.filter(year=datetime.now(tz=cur_tz).year).order_by('no').last()
        if not maxalarm:
            return 1
        else:
            return maxalarm.no + 1

    # inherited: comment, date, duration, location, participants
    key = models.CharField(max_length=50, help_text="Alarmstichwort")
    year = models.SmallIntegerField(default=datetime.now(tz=cur_tz).year,
                                    editable=False,
                                    help_text="Jahr des Alarms")
    no = models.SmallIntegerField(default=autoinc_num, editable=False,
                                  help_text="Laufende Alarmierungsnummer im Jahr")
    date = models.DateTimeField(default=datetime.now(tz=cur_tz))
    # HOw long did the event last, 00:00:00 and not status "aborted" implies ongoing
    duration = models.DurationField(default=timedelta(), help_text="Dauer (h:m:s)")
    # Adress, e.g. "Am Volksdorfer Markt 100"
    address = models.CharField(max_length=150, blank=True,
                               verbose_name="Adresse",
                               help_text="Straße & Hausnummer des Einsatzortes")
    # A geographical point/address, which can be used to center the map
    location = models.ForeignKey(Location, null=True, blank=True, editable=False,
                                 on_delete=models.SET_NULL)
    comment = models.CharField(max_length=255, blank=True)
    participants = models.ManyToManyField(
        User,
        blank=True,
        through='Alarm_members',
        through_fields=('event', 'user'),
    )
    # whether we went to the Alarm, responded=False implies we did not.
    responded = models.BooleanField(default=True)

    def is_ongoing(self):
        """whether the alarm is currently ongoing"""
        logging.error("duration",self.duration)
        return self.responded and self.duration == timedelta(seconds=0)

    def get_absolute_url(self):
        return reverse('alarm-detail', kwargs={'year': self.year, 'no': self.no})

    def __str__(self):
        return f"{self.key} #{self.no}"

    class Meta:
        get_latest_by = "date"
        unique_together = [['year', 'no']]
        ordering = ("-year", "-no")
        verbose_name_plural = _("Alarme")

class Dienst(models.Model):
    name = models.CharField(max_length=200, blank=True,
                            help_text="Titel des Dienstes")
    comment = models.CharField(max_length=255, blank=True)
    date = models.DateTimeField(default=datetime.now(tz=cur_tz))
    duration = models.DurationField(default="2:00:00", help_text="Dauer (h:m:s)")
    location = models.CharField(max_length=100, blank=True)
    participants = models.ManyToManyField(
        User,
        blank=True,
        through='Dienst_members',
        through_fields=('event', 'user'),
    )

    def get_absolute_url(self):
        return reverse('dienst-detail', kwargs={'pk': self.pk})

    def __str__(self):
        return self.name


class Role(models.Model):
    """Roles such as AGT, Maschinist, etc..."""
    name = models.CharField(max_length=100)
    icon = models.ImageField(upload_to="uploads/", max_length=255,
                              null=True, blank=True)

    def __str__(self):
        return self.name


class Alarm_members(models.Model):
    """ Through model connecting Events and invited/attending Users"""

    event = models.ForeignKey(Alarm, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    attendance = models.SmallIntegerField(choices=Attendance.choices,
                                          default=Attendance.YES,
                                          null=True, blank=True,
                                          help_text="Teilnahmestatus")
    role = models.ForeignKey(Role, null=True, blank=True, on_delete=models.CASCADE)
    attendance_reason = models.CharField(max_length=128, blank=True)

    def get_color(self):
        """Return color of the attendance"""
        return self.attendance.color
    
    def __str__(self):
        return f"{self.attendance} ({self.event}, {self.user.username})"

    class Meta:
        constraints = [
            models.UniqueConstraint(fields=['event', 'user'],
                                    name='unique_alarm_participation')
            ]
        ordering = ("event", "attendance", "role")

class Dienst_members(models.Model):
    """ Through model connecting Events and invited/attending Users"""

    event = models.ForeignKey(Dienst, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    attendance = models.SmallIntegerField(choices=Attendance.choices,
                                  default=Attendance.__empty__,
                                  help_text="Teilnahmestatus")
    role = models.ForeignKey(Role, null=True, blank=True, on_delete=models.CASCADE)
    attendance_reason = models.CharField(max_length=128, blank=True)

    def get_color(self):
        """Return color of the attendance"""
        return self.attendance.color
    
    def __str__(self):
        return f"{self.attendance} ({self.event}, {self.user.username})"

    class Meta:
        constraints = [
            models.UniqueConstraint(fields=['event', 'user'],
                                    name='unique_dienst_participation')
            ]
        ordering = ("event", "attendance", "role")

feuerwehr/forms.py
from django.forms import ModelForm
from feuerwehr.models import Alarm

class AlarmForm(ModelForm):
    class Meta:
        model = Alarm
        exclude = []
        #fields = ['name', 'title', 'birth_date']

feuerwehr/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Count, OuterRef, Subquery
from django.views.generic.base import TemplateView
from django.views.generic.edit import CreateView, UpdateView
from django.views.generic.detail import DetailView
from django.views.generic.list import ListView

from .forms import AlarmForm
from .models import Alarm, User

class HomepageView(TemplateView):
    template_name = "home.html"

class AlarmListView(LoginRequiredMixin,ListView):
    model = Alarm

class AlarmDetailView(LoginRequiredMixin,DetailView):
    model = Alarm

    def get_object(self, queryset=None):
        no = self.kwargs['no']
        year = self.kwargs.get('year', 2024)
        return self.model.objects.get(no=no,year=year)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['participants'] = self.object.alarm_members_set.all()
        return context


class AlarmCreateView(LoginRequiredMixin,CreateView):
    model = Alarm
    form_class = AlarmForm
    #fields = ['name']


class AlarmUpdateView(LoginRequiredMixin,UpdateView):
    model = Alarm

class UserListView(LoginRequiredMixin,ListView):
    model = User
    ordering = ["first_name", "last_name", "username"]


class UserDetailView(LoginRequiredMixin,DetailView):
    model = User
    slug_field = "username"
    slug_url_kwarg = "username"
    #def get_object(self, queryset=None):
    #    no = self.kwargs['no']
    #    year = self.kwargs.get('year', 2024)
    #    return self.model.objects.get(no=no,year=year)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # all alarms that have attendance "bestätigt" or "zugesagt"
        alarme = Alarm.objects.filter(participants=self.object, alarm_members__attendance__lte=2)
        context['alarme'] = alarme
        context['num_alarme'] = alarme.count()
        context['tot_alarme'] = Alarm.objects.count()
        return context

feuerwehr/templates/feuerwehr/alarm_detail.html
{% extends "feuerwehr/alarm_list.html" %}{% load static %}{% load l10n %}
{% block breadcrumb %}{{block.super}}<a href="{{ alarm.get_absolute_url }}">#{{ alarm.no }}</a>{% endblock %}
{% block title %}Alarm {{ alarm }}{% endblock %}
{% block extrahead %}
<link rel="stylesheet" type="text/css" href="https://unpkg.com/leaflet@1.9.4/dist/leaflet.css" crossorigin=""/> <!--https://unpkg.com/leaflet/dist/leaflet.css*-->
<link rel="stylesheet" type="text/css" href="{% static 'css/map.css' %}"/>
<script src="https://unpkg.com/leaflet@1.9.4/dist/leaflet.js" crossorigin=""></script> <!--https://unpkg.com/leaflet/dist/leaflet.js-->
{% endblock %}
{% block content %}
<table>
<tr class="odd"><td>Stichwort</td><td>{{alarm.key}}</td></tr>
<tr class="even"><td>Adresse</td><td>{{alarm.address}}</td></tr>
<tr class="odd"><td>Datum</td><td>{{alarm.date}}</td></tr>
<tr class="even"><td>Kommentar</td><td>{{alarm.comment}}</td></tr>
</table>
{#Map#}
<!--<iframe width="100%" height="350px" frameborder="0" allowfullscreen allow="geolocation" src="https://umap.openstreetmap.de/de/map/Volksdorf_50119?{% if alarm.location %}#17/{{alarm.location.lat|unlocalize}}/{{alarm.location.lon|unlocalize}}{% endif %}"></iframe><p><a href="https://umap.openstreetmap.de/de/map/Volksdorf_50119?searchControl=true{% if alarm.location %}#17/{{alarm.location.lat|unlocalize}}/{{alarm.location.lon|localize}}{% endif %}">See full screen</a></p>-->
<div id="map"></div>
<!--<script src="{% static 'js/map.js' %}" defer></script>-->
<script>
const copy =
  "&copy; <a href='https://www.openstreetmap.org/copyright'>OpenStreetMap</a>";
const url =
  "https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png";
const layer = L.tileLayer(url, {
  attribution: copy,
});
const map = L.map("map", {
    layers: [layer],
    zoom: 17,
});
  var hydrantIcon = L.icon({iconUrl: '{% static "img/hydrant.svg" %}',iconSize: [20,20]});
  fetch('{% static 'hydranten.geojson' %}')
    .then((response) => response.json())
    .then((hydrantGeoJson) => L.geoJSON(hydrantGeoJson,{
	pointToLayer: function (feature, latlng){
	    return L.marker(latlng, {icon: hydrantIcon});
	}
    }).addTo(map));
/*map.fitWorld(); , {
        pointToLayer: function (feature, latlng){
	    return L.marker(latlng, {icon: hydrantIcon});
	}
    }*/
{% if alarm.location %}map.setView([{{alarm.location.lat|unlocalize}},{{alarm.location.lon|unlocalize}}]);
  const marker1 = L.marker([{{alarm.location.lat|unlocalize}},{{alarm.location.lon|unlocalize}}],
			   {icon: L.icon({iconUrl: '{% static "img/fire.svg" %}',iconSize: [30,30]})}).addTo(map);
{%else%}
map.setView([53.6513, 10.1726], 16){% endif %}
</script>

<h4>Personen</h4>
<table>
{% for m in participants %}
<tr class="att_{{m.attendance}}"><td>{{ m.user }}</td>
  <td class="userlist">{%if m.role.icon %}<img src="{{MEDIA_URL}}{{m.role.icon}}" title="{{m.role}}"/>{% else %}{{m.role|default_if_none:""}}{% endif %}</td>
</tr>
{% endfor %}
</table>
{% endblock %}

feuerwehr/templates/feuerwehr/alarm_form.html
{% extends "feuerwehr/alarm_list.html" %}
{% block breadcrumb %}{{block.super}}<a href="#">Neuer Alarm</a>{% endblock %}
{% block title %}Neuer Alarm{% endblock %}
{% block content %}
<form method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save">
</form>

<table>
<tr><td></td><td>{{alarm.name}}</td></tr>
<tr><td></td><td>{{alarm.location}}</td></tr>
<tr><td></td><td>{{alarm.date}}</td></tr>
</table>
<h4>Personen</h4>
<table>
{% for participant in alarm.participants.all%}
<tr><td>{{ participant.user }}</td></tr>
{% endfor %}
</table>
{% endblock %}

feuerwehr/templates/feuerwehr/alarm_list.html
{% extends "base.html" %}
{% block breadcrumb %}{{ block.super }}<a href="{% url 'alarm-list' %}">Alarme</a>{% endblock %}
{% block title %}Alarme{% endblock %}
{% block content %}
<a href="{% url 'alarm-create' %}">NEUER ALARM</a>
<table>
{% for alarm in object_list %}
<tr class="{% cycle 'odd' 'even' %}">
  <td><a href="{{ alarm.get_absolute_url }}" class="{% if alarm.is_ongoing %}alarm_ongoing{% elif alarm.responded %}alarm_responded{% endif %}">{{ alarm }}</a>
  </td>
</tr>
{% empty %}
    <tr><td>Keine Alarme vorhanden.</td></tr>
{% endfor %}
</table>{% endblock %}